// ---- banco de ejercicios: modo "Encuentra el error" ----
// Cada ejercicio trae código con un error ya cargado en el editor.
// El usuario debe corregirlo para que la salida coincida con "expected".
const EXERCISES_BUG = {
  variables: {
    label: 'Variables',
    items: [
      { id: 'bug-variables-1', difficulty: 'facil', title: 'Nombre de variable equivocado', prompt: 'Este código debería imprimir <code>Hola Godot</code>, pero hay un error de tipeo en el nombre de una variable. Encuéntralo y corrígelo.', code: 'var msg = "Hola Godot"\nprint(mensaje)', expected: 'Hola Godot' },
      { id: 'bug-variables-2', difficulty: 'facil', title: 'Operador equivocado', prompt: 'Este código debería imprimir la <b>resta</b> de <code>a</code> menos <code>b</code>, pero usa el operador equivocado. Corrígelo para que imprima <code>7</code>.', code: 'var a = 12\nvar b = 5\nprint(a + b)', expected: '7' },
      { id: 'bug-variables-3', difficulty: 'facil', title: 'Orden de impresión', prompt: 'Este código debería imprimir primero el valor de <code>y</code> y luego el de <code>x</code>, pero están al revés. Corrige el orden.', code: 'var x = 4\nvar y = 9\nprint(x)\nprint(y)', expected: '9\n4' },
      { id: 'bug-variables-4', difficulty: 'medio', title: 'Faltan espacios', prompt: 'Este código debería imprimir exactamente <code>Kai tiene 30 puntos</code>, pero faltan espacios dentro de los textos. Corrígelo.', code: 'var nombre = "Kai"\nvar puntos = 30\nprint(nombre, "tiene", puntos, "puntos")', expected: 'Kai tiene 30 puntos' },
      { id: 'bug-variables-5', difficulty: 'medio', title: 'Argumento equivocado en typeof', prompt: 'Este código debería imprimir el tipo de dato de la variable <code>valor</code> (que es <code>3.5</code>), pero le está pasando otra cosa a <code>typeof()</code>. Corrígelo para que imprima <code>float</code>.', code: 'var valor = 3.5\nprint(typeof(3))', expected: 'float' },
      { id: 'bug-variables-6', difficulty: 'medio', title: 'Operandos invertidos', prompt: 'Este código debería imprimir <code>a</code> dividido entre <code>b</code>, pero los operandos de la división están al revés. Corrígelo para que imprima <code>3</code>.', code: 'var a = 9\nvar b = 3\nprint(b / a)', expected: '3' },
      { id: 'bug-variables-7', difficulty: 'facil', title: 'Operador de asignación equivocado', prompt: 'Este código debería restarle 8 a <code>contador</code>, pero usa el operador de sumar. Corrígelo para que imprima <code>12</code>.', code: 'var contador = 20\ncontador += 8\nprint(contador)', expected: '12' },
      { id: 'bug-variables-8', difficulty: 'medio', title: 'Falta convertir el tipo', prompt: 'Este código debería convertir <code>texto</code> a número antes de sumarle 5, pero olvida usar <code>int()</code>. Corrígelo para que imprima <code>20</code> en vez de concatenar texto.', code: 'var texto = "15"\nprint(texto + 5)', expected: '20' },
      { id: 'bug-variables-9', difficulty: 'facil', title: 'Falta usar abs()', prompt: 'Este código debería imprimir el valor absoluto de <code>n</code>, pero imprime <code>n</code> directamente. Corrígelo para que imprima <code>22</code>.', code: 'var n = -22\nprint(n)', expected: '22' },
      { id: 'bug-variables-10', difficulty: 'dificil', title: 'Umbral equivocado', prompt: 'Este código debería imprimir <code>true</code> porque el jugador está activo y tiene más de 0 vidas, pero el umbral de comparación es incorrecto. Corrígelo.', code: 'var activo = true\nvar vidas = 2\nprint(activo and vidas > 5)', expected: 'true' },
    ]
  },
  condicionales: {
    label: 'Condicionales',
    items: [
      { id: 'bug-condicionales-1', difficulty: 'facil', title: 'Comparación invertida', prompt: 'Con <code>num = 30</code> y <code>umbral = 20</code>, este código debería imprimir <code>"Mayor"</code>, pero el operador de comparación está invertido. Corrígelo.', code: 'var num = 30\nvar umbral = 20\nif num < umbral:\n    print("Mayor")\nelse:\n    print("Menor o igual")', expected: 'Mayor' },
      { id: 'bug-condicionales-2', difficulty: 'medio', title: 'Mensajes intercambiados', prompt: 'Con <code>num = -5</code>, este código debería imprimir <code>"Negativo"</code>, pero los mensajes de las ramas están intercambiados. Corrígelo.', code: 'var num = -5\nif num > 0:\n    print("Negativo")\nelif num < 0:\n    print("Positivo")\nelse:\n    print("Cero")', expected: 'Negativo' },
      { id: 'bug-condicionales-3', difficulty: 'facil', title: 'Condición de paridad invertida', prompt: 'Con <code>num = 17</code>, este código debería imprimir <code>"Impar"</code>, pero la condición de par/impar está al revés. Corrígelo.', code: 'var num = 17\nif num % 2 == 1:\n    print("Par")\nelse:\n    print("Impar")', expected: 'Impar' },
      { id: 'bug-condicionales-4', difficulty: 'dificil', title: 'Orden de ramas equivocado', prompt: 'Con <code>edad = 15</code>, este código debería imprimir <code>"Adolescente"</code>, pero el orden de las condiciones <code>elif</code> está mal y nunca revisa "menor a 13" primero. Corrígelo.', code: 'var edad = 15\nif edad < 18:\n    print("Niño")\nelif edad < 13:\n    print("Adolescente")\nelif edad < 65:\n    print("Adulto")\nelse:\n    print("Adulto mayor")', expected: 'Adolescente' },
      { id: 'bug-condicionales-5', difficulty: 'medio', title: 'Límite incorrecto', prompt: 'Con <code>nota = 6.0</code>, este código debería imprimir <code>"Aprobado"</code> (la nota mínima 6 aprueba), pero usa <code>&gt;</code> en vez de <code>&gt;=</code>. Corrígelo.', code: 'var nota = 6.0\nif nota > 6:\n    print("Aprobado")\nelse:\n    print("Reprobado")', expected: 'Aprobado' },
      { id: 'bug-condicionales-6', difficulty: 'medio', title: '"and" en vez de "or" (o viceversa)', prompt: 'Con <code>num = 9</code>, este código debería imprimir <code>"No"</code> porque 9 no es múltiplo de 3 <b>y</b> de 5 a la vez, pero usa <code>or</code> en vez de <code>and</code>. Corrígelo.', code: 'var num = 9\nif num % 3 == 0 or num % 5 == 0:\n    print("FizzBuzz")\nelse:\n    print("No")', expected: 'No' },
      { id: 'bug-condicionales-7', difficulty: 'medio', title: 'Igualdad vs. desigualdad', prompt: 'Con <code>nombre = "Mia"</code> y <code>objetivo = "Kai"</code>, este código debería imprimir <code>"No coincide"</code>, pero usa <code>!=</code> en vez de <code>==</code>, invirtiendo la lógica. Corrígelo.', code: 'var nombre = "Mia"\nvar objetivo = "Kai"\nif nombre != objetivo:\n    print("Coincide")\nelse:\n    print("No coincide")', expected: 'No coincide' },
      { id: 'bug-condicionales-8', difficulty: 'facil', title: 'Límite del rango equivocado', prompt: 'Con <code>x = 50</code>, este código debería imprimir <code>"En rango"</code> (el rango válido es 1 a 100), pero el límite superior está mal escrito. Corrígelo.', code: 'var x = 50\nif x >= 1 and x <= 10:\n    print("En rango")\nelse:\n    print("Fuera de rango")', expected: 'En rango' },
      { id: 'bug-condicionales-9', difficulty: 'medio', title: 'Falta el "not"', prompt: 'Con <code>n = 0</code>, este código debería imprimir <code>"Es cero"</code>, pero le falta el <code>not</code> para negar la condición. Corrígelo.', code: 'var n = 0\nif n:\n    print("Es cero")\nelse:\n    print("No es cero")', expected: 'Es cero' },
      { id: 'bug-condicionales-10', difficulty: 'dificil', title: 'Umbral de categoría equivocado', prompt: 'Con <code>nota = 82</code>, este código debería imprimir <code>"B"</code> (el umbral de B es 80), pero uno de los umbrales está mal escrito. Corrígelo.', code: 'var nota = 82\nif nota >= 90:\n    print("A")\nelif nota >= 85:\n    print("B")\nelif nota >= 70:\n    print("C")\nelse:\n    print("D")', expected: 'B' },
    ]
  },
  bucles: {
    label: 'Bucles',
    items: [
      { id: 'bug-bucles-1', difficulty: 'facil', title: 'Falta el último número', prompt: 'Este código debería imprimir los números del 1 al 5, pero el límite de <code>range()</code> está mal. Corrígelo.', code: 'for i in range(1, 5):\n    print(i)', expected: '1\n2\n3\n4\n5' },
      { id: 'bug-bucles-2', difficulty: 'facil', title: 'Suma incompleta', prompt: 'Este código debería sumar los números del 1 al 10 e imprimir <code>55</code>, pero el límite de <code>range()</code> deja fuera al 10. Corrígelo.', code: 'var suma = 0\nfor i in range(1, 10):\n    suma += i\nprint(suma)', expected: '55' },
      { id: 'bug-bucles-3', difficulty: 'medio', title: 'Fórmula equivocada', prompt: 'Este código debería imprimir la tabla del 3, pero usa <code>i*i</code> en vez de <code>3*i</code> para el resultado. Corrígelo.', code: 'for i in range(1, 6):\n    print(3, " x ", i, " = ", i*i)', expected: '3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15' },
      { id: 'bug-bucles-4', difficulty: 'facil', title: 'Paso equivocado', prompt: 'Este código debería imprimir los números pares del 2 al 10, pero incrementa de a 1 en vez de a 2. Corrígelo.', code: 'var i = 2\nwhile i <= 10:\n    print(i)\n    i += 1', expected: '2\n4\n6\n8\n10' },
      { id: 'bug-bucles-5', difficulty: 'medio', title: 'Condición de continue invertida', prompt: 'Este código debería imprimir todos los números del 1 al 10 <b>excepto</b> los múltiplos de 3, pero la condición del <code>continue</code> está invertida (salta los que no son múltiplos). Corrígelo.', code: 'for i in range(1, 11):\n    if i % 3 != 0:\n        continue\n    print(i)', expected: '1\n2\n4\n5\n7\n8\n10' },
      { id: 'bug-bucles-6', difficulty: 'medio', title: 'Falta el paso negativo', prompt: 'Este código debería contar del 5 al 1 en cuenta regresiva, pero a <code>range()</code> le falta el paso negativo, así que no imprime nada. Corrígelo.', code: 'for i in range(5, 0):\n    print(i)', expected: '5\n4\n3\n2\n1' },
      { id: 'bug-bucles-7', difficulty: 'dificil', title: 'Condición de corte equivocada', prompt: 'Este código debería sumar 0+1+2+3+4 y detenerse antes de sumar el 5, imprimiendo <code>10</code>, pero la condición del <code>break</code> deja pasar una vuelta de más. Corrígelo.', code: 'var i = 0\nvar suma = 0\nwhile true:\n    suma += i\n    i += 1\n    if i > 5:\n        break\nprint(suma)', expected: '10' },
      { id: 'bug-bucles-8', difficulty: 'medio', title: 'Rango interno equivocado', prompt: 'Este código debería imprimir las 4 combinaciones de <code>i</code> y <code>j</code> entre 1 y 2, pero el bucle interno usa un rango equivocado y solo genera 2 combinaciones. Corrígelo.', code: 'for i in range(1, 3):\n    for j in range(2, 3):\n        print(i, "-", j)', expected: '1-1\n1-2\n2-1\n2-2' },
      { id: 'bug-bucles-9', difficulty: 'medio', title: 'Filtro invertido', prompt: 'Este código debería imprimir solo los números pares del 1 al 10, pero la condición del <code>continue</code> está invertida y deja pasar los impares. Corrígelo.', code: 'for i in range(1, 11):\n    if i % 2 == 0:\n        continue\n    print(i)', expected: '2\n4\n6\n8\n10' },
      { id: 'bug-bucles-10', difficulty: 'facil', title: 'Variable equivocada dentro del bucle', prompt: 'Este código debería imprimir cada letra de <code>"sol"</code> por separado, pero dentro del bucle imprime la palabra completa en vez de la letra actual. Corrígelo.', code: 'var palabra = "sol"\nfor c in palabra:\n    print(palabra)', expected: 's\no\nl' },
    ]
  },
  funciones: {
    label: 'Funciones',
    items: [
      { id: 'bug-funciones-1', difficulty: 'facil', title: 'Falta el return', prompt: 'Esta función debería retornar el saludo armado, pero le falta la palabra <code>return</code>, así que siempre retorna un valor vacío. Corrígela para que imprima <code>Hola, Mundo!</code>.', code: 'func saludar(nombre):\n    "Hola, " + nombre + "!"\nprint(saludar("Mundo"))', expected: 'Hola, Mundo!' },
      { id: 'bug-funciones-2', difficulty: 'facil', title: 'Operador equivocado en el return', prompt: 'Esta función debería sumar <code>a</code> y <code>b</code>, pero está restando. Corrígela para que <code>sumar(4, 9)</code> imprima <code>13</code>.', code: 'func sumar(a, b):\n    return a - b\nprint(sumar(4, 9))', expected: '13' },
      { id: 'bug-funciones-3', difficulty: 'medio', title: 'Condición de paridad invertida', prompt: 'Esta función debería retornar <code>true</code> cuando el número es par, pero la condición está invertida. Corrígela para que imprima <code>true</code> y luego <code>false</code>.', code: 'func es_par(n):\n    return n % 2 == 1\nprint(es_par(10))\nprint(es_par(7))', expected: 'true\nfalse' },
      { id: 'bug-funciones-4', difficulty: 'dificil', title: 'Falta multiplicar en la recursión', prompt: 'Esta función recursiva debería calcular el factorial multiplicando <code>n</code> en cada llamada, pero olvida la multiplicación. Corrígela para que <code>factorial(6)</code> imprima <code>720</code>.', code: 'func factorial(n):\n    if n <= 1:\n        return 1\n    return factorial(n - 1)\nprint(factorial(6))', expected: '720' },
      { id: 'bug-funciones-5', difficulty: 'medio', title: 'Comparación invertida', prompt: 'Esta función debería retornar el mayor de los dos números, pero la comparación está invertida y retorna el menor. Corrígela para que <code>mayor(15, 9)</code> imprima <code>15</code>.', code: 'func mayor(a, b):\n    if a < b:\n        return a\n    else:\n        return b\nprint(mayor(15, 9))', expected: '15' },
      { id: 'bug-funciones-6', difficulty: 'facil', title: 'Falta parte del texto', prompt: 'Esta función debería imprimir <code>Chau, Tom!</code>, pero le falta el signo de exclamación en la concatenación. Corrígela.', code: 'func despedir(nombre):\n    print("Chau, " + nombre)\ndespedir("Tom")', expected: 'Chau, Tom!' },
      { id: 'bug-funciones-7', difficulty: 'medio', title: 'Divisor equivocado', prompt: 'Esta función debería calcular el promedio de tres números dividiendo entre 3, pero divide entre 2. Corrígela para que <code>promedio(4, 5, 9)</code> imprima <code>6</code>.', code: 'func promedio(a, b, c):\n    return (a + b + c) / 2\nprint(promedio(4, 5, 9))', expected: '6' },
      { id: 'bug-funciones-8', difficulty: 'dificil', title: 'Llamada recursiva equivocada', prompt: 'Esta función recursiva de Fibonacci debería llamarse a sí misma con <code>n-1</code> y <code>n-2</code>, pero llama dos veces con <code>n-1</code>. Corrígela para que <code>fib(7)</code> imprima <code>13</code>.', code: 'func fib(n):\n    if n <= 1:\n        return n\n    return fib(n - 1) + fib(n - 1)\nprint(fib(7))', expected: '13' },
      { id: 'bug-funciones-9', difficulty: 'medio', title: 'Condición de paridad invertida', prompt: 'Esta función debería retornar <code>true</code> solo si encuentra un número <b>par</b> en la lista, pero revisa si es impar. Con <code>[1, 3, 5, 7]</code> (sin pares) debería imprimir <code>false</code>. Corrígela.', code: 'func contiene_par(lista):\n    for n in lista:\n        if n % 2 == 1:\n            return true\n    return false\nprint(contiene_par([1, 3, 5, 7]))', expected: 'false' },
      { id: 'bug-funciones-10', difficulty: 'medio', title: 'Falta elevar al cuadrado', prompt: 'Esta función debería sumar el cuadrado de <code>a</code> más el cuadrado de <code>b</code>, pero a <code>b</code> se le olvidó elevarlo al cuadrado. Corrígela para que <code>suma_cuadrados(3, 4)</code> imprima <code>25</code>.', code: 'func cuadrado(n):\n    return n * n\nfunc suma_cuadrados(a, b):\n    return cuadrado(a) + b\nprint(suma_cuadrados(3, 4))', expected: '25' },
    ]
  },
  arrays: {
    label: 'Arrays',
    items: [
      { id: 'bug-arrays-1', difficulty: 'facil', title: 'Nombre de variable equivocado', prompt: 'Este código debería imprimir el array completo, pero tiene un error de tipeo en el nombre de la variable al imprimir. Corrígelo.', code: 'var numeros = [10, 20, 30]\nprint(numero)', expected: '[10, 20, 30]' },
      { id: 'bug-arrays-2', difficulty: 'facil', title: 'Falta llamar a append', prompt: 'Este código debería agregar el 4 al array con <code>.append()</code>, pero solo escribe el número suelto sin agregarlo. Corrígelo para que imprima <code>[1, 2, 3, 4]</code>.', code: 'var numeros = [1, 2, 3]\n4\nprint(numeros)', expected: '[1, 2, 3, 4]' },
      { id: 'bug-arrays-3', difficulty: 'medio', title: 'Método equivocado', prompt: 'Este código debería imprimir el tamaño del array con <code>.size()</code>, pero usa un método que no existe para arrays. Corrígelo.', code: 'var frutas = ["manzana", "pera", "uva", "kiwi"]\nprint(frutas.length())', expected: '4' },
      { id: 'bug-arrays-4', difficulty: 'facil', title: 'Valor inicial equivocado', prompt: 'Este código debería sumar los elementos del array partiendo de 0, pero <code>suma</code> arranca en 10. Corrígelo para que imprima <code>66</code>.', code: 'var numeros = [4, 8, 15, 16, 23]\nvar suma = 10\nfor n in numeros:\n    suma += n\nprint(suma)', expected: '66' },
      { id: 'bug-arrays-5', difficulty: 'facil', title: 'Buscando el elemento equivocado', prompt: 'Este código debería comprobar si el array contiene <code>"verde"</code>, pero está buscando <code>"amarillo"</code>, que no está. Corrígelo para que imprima <code>true</code>.', code: 'var colores = ["rojo", "verde", "azul"]\nprint(colores.has("amarillo"))', expected: 'true' },
      { id: 'bug-arrays-6', difficulty: 'medio', title: 'Elimina el valor equivocado', prompt: 'Este código debería eliminar el valor <code>3</code> de la lista, pero está eliminando el <code>2</code>. Corrígelo para que imprima <code>[1, 2, 4, 5]</code>.', code: 'var lista = [1, 2, 3, 4, 5]\nlista.erase(2)\nprint(lista)', expected: '[1, 2, 4, 5]' },
      { id: 'bug-arrays-7', difficulty: 'facil', title: 'Falta invertir el array', prompt: 'Este código debería invertir el array antes de imprimirlo, pero olvida llamar a <code>.reverse()</code>. Corrígelo para que imprima <code>[c, b, a]</code>.', code: 'var letras = ["a", "b", "c"]\nprint(letras)', expected: '[c, b, a]' },
      { id: 'bug-arrays-8', difficulty: 'dificil', title: 'Falta duplicar el array', prompt: 'Este código debería copiar el array con <code>.duplicate()</code> para que modificar la copia no afecte al original, pero solo copia la referencia. Corrígelo para que <code>original</code> quede como <code>[1, 2, 3]</code> aunque <code>copia</code> le agregue un 4.', code: 'var original = [1, 2, 3]\nvar copia = original\ncopia.append(4)\nprint(original)\nprint(copia)', expected: '[1, 2, 3]\n[1, 2, 3, 4]' },
      { id: 'bug-arrays-9', difficulty: 'medio', title: 'Falta invertir después de ordenar', prompt: 'Este código debería ordenar el array de mayor a menor, pero le falta llamar a <code>.reverse()</code> después de <code>.sort()</code>. Corrígelo para que imprima <code>[5, 4, 3, 2, 1]</code>.', code: 'var n = [5, 1, 4, 2, 3]\nn.sort()\nprint(n)', expected: '[5, 4, 3, 2, 1]' },
      { id: 'bug-arrays-10', difficulty: 'medio', title: 'Condición de filtro invertida', prompt: 'Este código debería quedarse solo con los números <b>mayores</b> a 10, pero la condición está invertida y se queda con los menores. Corrígelo para que imprima <code>[12, 20]</code>.', code: 'var numeros = [3, 8, 12, 7, 20, 5]\nvar mayores = []\nfor n in numeros:\n    if n < 10:\n        mayores.append(n)\nprint(mayores)', expected: '[12, 20]' },
    ]
  },
  diccionarios: {
    label: 'Diccionarios',
    items: [
      { id: 'bug-diccionarios-1', difficulty: 'facil', title: 'Clave con error de tipeo', prompt: 'Este código debería imprimir el nombre de la persona, pero la clave usada al acceder tiene un error de tipeo. Corrígelo para que imprima <code>Eli</code>.', code: 'var persona = {"nombre": "Eli", "edad": 25}\nprint(persona["nombres"])', expected: 'Eli' },
      { id: 'bug-diccionarios-2', difficulty: 'facil', title: 'Falta agregar la clave', prompt: 'Este código debería agregar la clave <code>"b"</code> con valor 2 antes de imprimir, pero se olvida de hacerlo. Corrígelo para que imprima <code>{"a": 1, "b": 2}</code>.', code: 'var datos = {"a": 1}\nprint(datos)', expected: '{"a": 1, "b": 2}' },
      { id: 'bug-diccionarios-3', difficulty: 'medio', title: 'Método equivocado', prompt: 'Este código debería imprimir el tamaño del diccionario con <code>.size()</code>, pero usa un método que no existe. Corrígelo.', code: 'var inventario = {"espada": 1, "escudo": 2, "pocion": 5}\nprint(inventario.len())', expected: '3' },
      { id: 'bug-diccionarios-4', difficulty: 'dificil', title: 'keys() vs values()', prompt: 'Este código debería recorrer las <b>claves</b> del diccionario con <code>.keys()</code> para poder usarlas como índice, pero recorre <code>.values()</code> por error. Corrígelo para que imprima <code>Ana: 90</code> y <code>Leo: 75</code>.', code: 'var puntajes = {"Ana": 90, "Leo": 75}\nfor clave in puntajes.values():\n    print(clave, ": ", puntajes[clave])', expected: 'Ana: 90\nLeo: 75' },
      { id: 'bug-diccionarios-5', difficulty: 'facil', title: 'Revisando la clave equivocada', prompt: 'Este código debería comprobar si existe la clave <code>"peras"</code> (que no está en el diccionario), pero está revisando <code>"manzanas"</code>, que sí existe. Corrígelo para que imprima <code>false</code>.', code: 'var stock = {"manzanas": 10}\nprint(stock.has("manzanas"))', expected: 'false' },
      { id: 'bug-diccionarios-6', difficulty: 'medio', title: 'Elimina la clave equivocada', prompt: 'Este código debería eliminar la clave <code>"b"</code>, pero está eliminando <code>"a"</code>. Corrígelo para que imprima <code>{"a": 1, "c": 3}</code>.', code: 'var d = {"a": 1, "b": 2, "c": 3}\nd.erase("a")\nprint(d)', expected: '{"a": 1, "c": 3}' },
      { id: 'bug-diccionarios-7', difficulty: 'facil', title: 'Valor inicial equivocado', prompt: 'Este código debería sumar los precios partiendo de 0, pero <code>total</code> arranca en 5. Corrígelo para que imprima <code>9</code>.', code: 'var precios = {"pan": 2, "leche": 3, "huevo": 4}\nvar total = 5\nfor clave in precios.keys():\n    total += precios[clave]\nprint(total)', expected: '9' },
      { id: 'bug-diccionarios-8', difficulty: 'medio', title: 'Falta el "not"', prompt: 'Este código debería agregar la clave <code>"pera"</code> solo si <b>no</b> existe todavía, pero le falta el <code>not</code>, así que nunca se agrega. Corrígelo para que imprima <code>{"manzana": 5, "pera": 0}</code>.', code: 'var stock = {"manzana": 5}\nif stock.has("pera"):\n    stock["pera"] = 0\nprint(stock)', expected: '{"manzana": 5, "pera": 0}' },
      { id: 'bug-diccionarios-9', difficulty: 'medio', title: 'Clave con error de tipeo', prompt: 'Este código debería acceder a la clave <code>"items"</code>, pero está escrita en singular. Corrígelo para que imprima <code>2</code>.', code: 'var jugador = {"nombre": "Kai", "items": ["espada", "escudo"]}\nprint(jugador["item"].size())', expected: '2' },
      { id: 'bug-diccionarios-10', difficulty: 'dificil', title: 'keys() vs values()', prompt: 'Este código debería recorrer los <b>valores</b> (las edades) con <code>.values()</code> para compararlos con 18, pero recorre <code>.keys()</code> (los nombres) por error. Corrígelo para que imprima <code>2</code>.', code: 'var edades = {"Ana": 15, "Leo": 22, "Sol": 9, "Max": 30}\nvar adultos = 0\nfor edad in edades.keys():\n    if edad >= 18:\n        adultos += 1\nprint(adultos)', expected: '2' },
    ]
  },
};
